### ISSUE TITLE
Document everything

### ISSUE THREAD

**Issue by jfhbrook** [flatiron/blacksmith#20]
There _is_ documentation for blacksmith, but it's at least 4 weeks stale.

**Comment by mmalecki** [comment]
![Document all the things](http://i.qkme.me/35f59z.jpg)

**Comment by jfhbrook** [comment]
Not gonna lie, I almost used "document all the things" for this issue's title.

**Comment by indexzero** [comment]
ALL THE THINGS ARE DOCUMENTED in `blacksmith@1.0.0`
