### ISSUE TITLE
Add an ignore flag for the ToC

### ISSUE THREAD

**Issue by jfhbrook** [flatiron/blacksmith#21]
For example, on a blog with some extra pages, the extra pages (such as "archive", "about", etc.) will show up in the ToC.

Maybe the page.json can look like:

```
{
  "toc": {
    "index": false
  }
}
```

Commentary appreciated!

**Comment by optikfluffel** [comment]
+1 :)

**Comment by indexzero** [comment]
Not sure if this is resolved in `blacksmith@1.0.0`, but after a rewrite it's probably not relevant.
