### ISSUE TITLE
nice way for users to extend blacksmith's behavior on a per-blog basis

### ISSUE THREAD

**Issue by jfhbrook** [flatiron/blacksmith#26]
In a refactor, it would be nice to consider per-blog plugins from the start. This way, blacksmith can implement opinionated but easily-override-able behaviors.

(This makes me wonder, though, if blacksmith is suffering from feature creep.)

**Comment by indexzero** [comment]
This should be possible with `pages`, `layouts` and `partials` in `blacksmith@1.0.0`
