### ISSUE TITLE
Features needed

### ISSUE THREAD

**Issue by itwars** [flatiron/blacksmith#32]
I really think I'll used **Blacksmith** instead on _Octopress_ ... Anyway some keys features are needed to have an awesome blog :
- categories
- pagination
- tags

For optimizing speed adding a **CSS+JS compressor**, and ask for **URI encoded IMG** :)

Thank's

**Comment by jfhbrook** [comment]
Hi there!

I'm going to close this issue, but only because I created issues #35 and #36 instead. Thanks for the feedback!
