### ISSUE TITLE
The "after the break" algorithm should be more clever.

### ISSUE THREAD

**Issue by jfhbrook** [flatiron/blacksmith#38]
Currently, the "after the break" algorithm simply looks for the first header smaller than or equal to an h2. However, if the author doesn't have this in mind the results can, well, be surprising.

A smarter algorithm could clip after a certain number of paragraphs and up to/including the last header. Alternately, an "after the break" tag (similar to the snippets tag) could be used.

**Comment by indexzero** [comment]
This could be more intelligent, but right now `##!!truncate` is doing the trick.
