### ISSUE TITLE
cannot deploy to nodejitsu

### ISSUE THREAD

**Issue by jmonster** [flatiron/blacksmith#41]
``` bash
error:  Error running command deploy
error:  Nodejitsu Error (500): Internal Server Error
error:  
error:  There was an error while attempting to start your application.
error:  Error spawning drone
error:  Script prematurely exited
error:  
error:  This type of error is usually a user error.
error:  Error output from your application:
error:  
error:  node.js:201
error:          throw e; // process.nextTick error, or 'error' event on first tick
error:                ^
error:  TypeError: undefined is not a function
error:      at Object.<anonymous> (/usr/local/src/domino/blacksmith-blog/domino/bin/server:3:18)
error:      at Module._compile (module.js:432:26)
error:      at Object..js (module.js:450:10)
error:      at Module.load (module.js:351:31)
error:      at Function._load (module.js:310:12)
error:      at Function.runMain (module.js:470:10)
error:      at Array.1 (/root/haibu-orchestra/node_modules/haibu/node_modules/haibu-carapace/lib/carapace.js:190:30)
error:      at EventEmitter._tickCallback (node.js:192:40)
info:   Nodejitsu not ok
```

**Comment by jfhbrook** [comment]
It works locally for me, with chrome. What version of the server is installed for you? I hard-set it to v0.1.x some time ago.

**Comment by jmonster** [comment]
I've got it working locally now (something was using port 8080 and blacksmith inaccurately reported that it was running on 8080 -- it actually failed to get 8080)

The error remains when trying to deploy with nodejitsu. I've tried altering the http-server value in package.json to be 0.1.x and  node 0.6.x but it instead errors on not finding the http-server module when its set to 0.1.x ... other values yield the undefined is not a function message.

node bin/server

also triggers the same error message

**Comment by jfhbrook** [comment]
Hi @jmonster,

I believe what happened was that you started with one of the scaffolds, right? The package.json in your blacksmith site folder should look like this:

https://github.com/flatiron/blacksmith-sites/blob/8609640e3323fffa9647844fe4abd9d74185a423/sites/blog/package.json

Basically, the jitsu deploy doesn't use the same http-server as the blacksmith preview command; While blacksmith preview uses the version of http-server included with blacksmith, your deployed blog uses the version expected to coexist with your blog files.

I've fixed the latest blacksmith-sites such that this should work correctly. Please give it a try!

**Comment by jmonster** [comment]
THANK YOU.

**Comment by jfhbrook** [comment]
...I'll take that to mean it worked. Splendid!
