### ISSUE TITLE
Incorrect markup generated on front page

### ISSUE THREAD

**Issue by GreyDev** [flatiron/blacksmith#42]
Using both the master and refactored branches, the initial "blacksmith init" creates a post entitled "First post". 

Upon "blacksmith generate", the rendered HTML lists the post title as "My awesome blog" on the front page. 
On the article page itself, the post title is correct.

Posts created using "blacksmith post" also generates an incorrect front page. Again, the post title is corrected on the article page.

Any idea what could be causing this?

**Comment by jfhbrook** [comment]
Not yet, but I'll take a look!

**Comment by jfhbrook** [comment]
Keep in mind: The refactor branch is not ready for use.

**Comment by GreyDev** [comment]
I found the bug in master and couldn't fix it myself so switched over to refactored to see if it had been resolved. When I found it hadn't, I figured it was time for a bug report :)

**Comment by jfhbrook** [comment]
Hi GreyDev,

I was unable to reproduce your issue. There are two suggestions I can give you though:
1. Make sure your site's [config.json](https://github.com/flatiron/blacksmith-sites/blob/master/sites/blog/config.json) is complete, as blacksmith looks here to figure out your site's title.
2. `blacksmith post` isn't very smart. When you run `blacksmith post` it will make a sub-page (which is good for blog posts but not for a front page). However, if you move the files out of the `./pages/first-post` directory into `./pages` it should work.

If you have further difficulties try finding me in #nodejitsu on irc.freenode.net .

**Comment by deepseafish** [comment]
I have the same problem as GreyDev. Installed blacksmith like suggested in docu, generated a blog page and did a 'blacksmith generate'. Every post on the frontpage has a title "My awesome blog".

**Comment by jfhbrook** [comment]
Hi @deepseafish,

What does your config.json look like?

**Comment by deepseafish** [comment]
Hi Joshua,

it's the default one. Didn't modify it. I can send it to you tonight when I'm back from work.

**Comment by jfhbrook** [comment]
Okay, because the default blog title is "My awesome blog" and you can change it with the `config.json`.

**Comment by deepseafish** [comment]
This is my config.json:

``` json
{
  "title": "My Awesome Blog",
  "url": "my.blog.local",
  "author": "Me",
  "description": "My awesome blog!",
  "tags": [
    "awesome",
    "blog"
  ]
}
```

...and this is the result (http://localhost:8080/): http://imgur.com/UanzM

**Comment by GreyDev** [comment]
Just to confirm; This is the same issue I was experiencing deepseafish.

**Comment by jcftang** [comment]
I came across this problem as well, I think it has to do with "<span class="title"></span>" and the actual <title> tag itself, I never got to the bottom of this.

**Comment by optikfluffel** [comment]
Same problem here =/

**Comment by jfromaniello** [comment]
I have the same problem, it seems (from my understanding) that weld sets the title of the articles equals to the title of the blog in this page.... but surprisingly it works fine on the article page which also show the two titles.

**Comment by optikfluffel** [comment]
+1
