### ISSUE TITLE
Integrating LESS and reducing template duplication?

### ISSUE THREAD

**Issue by KingScooty** [flatiron/blacksmith#45]
So i know microtemplating is avoided with blacksmith. However, how would i go about integrating LESS so that .less stylesheets are compiled into css in the public folder?

I really dig how blacksmith is setup, but LESS is a bit part of my workflow and i'd love to get it integrated.
Also, if i wanted to breakdown the templates so that code isn't duplicated in every template file, how would i go about it in a way that doesn't bloat blacksmith? Is there a way? Or would i have to resort to a microformat?

Code duplication and lack of Less are the only issues i have and would love to come up with work arounds for them.

**Comment by dscape** [comment]
There's pending bugs that are probably more urgent that adding less, so f you like this idea I would suggest sending a PR.

It's always good practice to do so in open source :)

Glad you love `blacksmith` :)

**Comment by indexzero** [comment]
Template duplication has been resolved by `layouts` and `partials`
