### ISSUE TITLE
Switch from marked to faster parser written in C (sundown): Robotskirt

### ISSUE THREAD

**Issue by przemoc** [flatiron/blacksmith#46]
Currently blacksmith uses [marked](https://github.com/chjj/marked), which is fine and relatively fast. But there is a faster one, [Robotskirt](https://github.com/benmills/robotskirt) based on the parser written in C: [sundown](https://github.com/tanoku/sundown), the one internally used by GitHub. As marked by default uses GitHub Flavored Markdown, it should be possible to perform the switch transparently I guess.

The only problem atm is that Robotskirt is in the process of making some changes to upgrade to recent sundown version (see [Issue 16](https://github.com/benmills/robotskirt/issues/16)) and do some other improvements (see last comments of [Issue 11](https://github.com/benmills/robotskirt/pull/11#issuecomment-6360801)), thus such switch possibly shouldn't happen before.

**Comment by mmalecki** [comment]
We're not going to switch to a compiled module because that makes installation harder. We try to avoid compiled modules whenever possible.
Also, `marked` is relatively fast.
