### ISSUE TITLE
Switch from deprecated Weld to more robust template solution: plates

### ISSUE THREAD

**Issue by przemoc** [flatiron/blacksmith#47]
Currently blacksmith uses deprecated [Weld](https://github.com/hij1nx/weld), which is fine, but no longer developed (beside bug fixing). Weld has been superseded by [plates](https://github.com/flatiron/plates). Maybe it is worth to consider a change of template solution within blacksmith?

**Comment by dscape** [comment]
@przemoc send a pr, we will take it :)

Please include tests

**Comment by vibegui** [comment]
This would really indicate that the project is going. For all I know, it seems abandoned... And yet I'd like to use it.

**Comment by jfhbrook** [comment]
It's just been low priority is all. We may find the bandwidth to rev up the blacksmith dev engine relatively soon though!

**Comment by indexzero** [comment]
This is fixed in `blacksmith@1.0.0`
