### ISSUE TITLE
./post1/post1 static hosting on s3

### ISSUE THREAD

**Issue by n2p5** [flatiron/blacksmith#53]
I am hosting my blog in static files on s3, when I am on index.html, clicking on the title of a blog post works properly by resolving to mysite.com/post1 . If I am on the specific post page and click the title again, it tries to resolve to mysite.com/post1/post1

This only happens when I upload to s3, not from 

``` bash
blacksmith preview
```

**Comment by indexzero** [comment]
This should be fixed in `blacksmith@1.0.0`
