### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by juandopazo** [flatiron/blacksmith#59]
Hi!

I installed Blacksmith via npm and when I tried to run `blacksmith preview` on a newly created blog I get errors like Winston trying to use `process.getuid()` which isn't supported in Windows. Is Windows support planned for Blacksmith?

**Comment by Jarod-stewart** [comment]
This is still a problem. Is it just a windows problem? Guess I will hop on my Mac. :-\

**Comment by jfhbrook** [comment]
Windows support for blacksmith depends on windows support for jsdom, which I'm guessing isn't on the road map.

**Comment by juandopazo** [comment]
The issue with `progress.getuid()` is on the Winston module. It was fixed in recent versions of Winston. Blacksmith depends on Winston and on Flatiron which uses Winston. Updating both will probably fix most issues. I haven't had any problems with jsdom on Windows yet.

**Comment by indexzero** [comment]
This should be resolved in `1.0.0`
