### ISSUE TITLE
Invalid HTML generated

### ISSUE THREAD

**Issue by pdeszynski** [flatiron/blacksmith#60]
Blacksmith does not generate valid HTML. Main problems are as follow:
- missing doctype declaration
- nav missess `<ul>` tag
- time is in wrong format (inside `<time>` tag)

On all other pages than index doctype and ul are present and in correct place.

To reproduce just:
- blacksmith init
- blackmith generate
- open file `public/index.html`

**Comment by indexzero** [comment]
Not sure if this is resolved in `blacksmith@1.0.0`, but after a rewrite it's probably not relevant.
