### ISSUE TITLE
Blacksmith init does not work

### ISSUE THREAD

**Issue by kartast** [flatiron/blacksmith#64]
When i run this line

```
    blacksmith init
```

this errors appear

```
    Rendering: init
    Path init does not exist
```

Am i doing something wrong here?

**Comment by Southern** [comment]
Looks like it was removed in the latest update that was created during the NKO hackfest.

/cc @indexzero

**Comment by kartast** [comment]
Should I use older version then? Or any workaround?

**Comment by Southern** [comment]
I would suggest trying an older version for now, but I don't know if you'll be able to use the one you generate with the old version with the new version. I'll have to let @indexzero confirm that.

**Comment by kartast** [comment]
Great, thanks!

**Comment by indexzero** [comment]
@kartast Yes use the old version. `blacksmith` was _completely rewritten_ from the ground up with no attention paid to backwards compatibility.

This will not be fixed in the near future or maybe ever: http://blog.flatironjs.org/01-a-whole-new-blacksmith#no-backwards-compatibility
