### ISSUE TITLE
npm version still at 0.0.13

### ISSUE THREAD

**Issue by n2p5** [flatiron/blacksmith#72]
I am stoked about this new version and I am ready to try it out, but it appears that npm still has the old version 0.0.13 in the repos. Any idea when this will get updated?

**Comment by gorsti** [comment]
you can ask npm to install 1.1.2 using
'npm install blacksmith@1.1.2 -g'

**Comment by blakmatrix** [comment]
@GORSTI is correct, We will update npm to default to later versions once we feel it is more appropriate.
