### ISSUE TITLE
Newly installed blacksmith fails to build a site _ 1.1.3 

### ISSUE THREAD

**Issue by taboca** [flatiron/blacksmith#79]
I was using blacksmith prior released like a charm to build about two web sites I have. Then I learned about the new version and decided to give it a try. Right after installing I had problems with Mac OS X and also with a fresh Debian installation. The error I get is the following: 

```
Rendering: test
Error rendering: test
{ [Error: ENOENT, open 'test/.blacksmith'] errno: 34, code: 'ENOENT', path: 'test/.blacksmith' }
[ 'Error: ENOENT, open \'test/.blacksmith\'' ]

/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
    at common.readAll (/usr/local/lib/node_modules/blacksmith/lib/blacksmith/common.js:69:11)
    at Object.oncomplete (fs.js:297:15)
```

**Comment by pksunkara** [comment]
blacksmith@1.0.0 has zero backwards compatibility with previous versions of blacksmith

Read more in here: http://blog.flatironjs.org/01-a-whole-new-blacksmith
