### ISSUE TITLE
async Error encountered while running blacksmith command

### ISSUE THREAD

**Issue by creatovisguru** [flatiron/blacksmith#80]
Node version: v0.8.9
I just installed blacksmith from npm, created a new directory and "cd" into it, ran the "blacksmith" command and received the following error:

$: blacksmith
Rendering: /Users/bdean/BenjaminDean.com
Error rendering: /Users/bdean/BenjaminDean.com
{ [Error: ENOENT, open '/Users/bdean/BenjaminDean.com/.blacksmith']
  errno: 34,
  code: 'ENOENT',
  path: '/Users/bdean/BenjaminDean.com/.blacksmith' }
[ 'Error: ENOENT, open \'/Users/bdean/BenjaminDean.com/.blacksmith\'' ]
1

/Users/bdean/.nvm/v0.8.9/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/Users/bdean/.nvm/v0.8.9/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
    at common.readAll (/Users/bdean/.nvm/v0.8.9/lib/node_modules/blacksmith/lib/blacksmith/common.js:70:11)
    at Object.oncomplete (fs.js:297:15)

Did I do something incorrectly or have a bad dependency?

**Comment by creatovisguru** [comment]
Duh...

I should probably try and finish reading the entire README.md before creating an issue eh?

Consider this a non-issue caused by lack of caffeine.

**Comment by rgaspary** [comment]
I get the same error but I have no idea what you saw in the readme that made more sence. Please share this knowledge upon this noob. I read both you comments and the readme and all I heard in my mind was WOOSH!!!

**Comment by gerbenjacobs** [comment]
I tried to run `blacksmith init` and got the same error.
