### ISSUE TITLE
Issue generating blacksmith site. 

### ISSUE THREAD

**Issue by taboca** [flatiron/blacksmith#83]
This is the error I get when trying

blacksmith

after creating a .blacksmith dir. Nevertheless the documentation says blacksmith should be the one trying to create the ".blacksmith" directory. 

Thanks 

```
endering: /Users/marciogalli/Desktop/blog

/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
    if (!arr.length) {
            ^
TypeError: Cannot read property 'length' of undefined
at Object.async.forEach (/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
at common.readAll (/usr/local/lib/node_modules/blacksmith/lib/blacksmith/common.js:69:11)
at Object.oncomplete (fs.js:297:15)
```

**Comment by taboca** [comment]
I know a lot of bugs that you guys are marking as closed but you fail to realize your documentation gives the impression that blacksmith generates dummy files.

**Comment by mmalecki** [comment]
I went through the docs and nothing suggests that `blacksmith` should generate `.blacksmith` file (not directory, it's a file). You have to create one yourself. Syntax is explained in the README.
