### ISSUE TITLE
Failure to generate an empty blog

### ISSUE THREAD

**Issue by igouss** [flatiron/blacksmith#98]
Provide a better error message.

li656-170% /home/i.gouss/.npm/blacksmith/1.1.3/package/bin/blacksmith /home/i.gouss/web/blog
Rendering: /home/i.gouss/web/blog

/home/i.gouss/node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/home/i.gouss/node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/async/lib/async.js:81:17)
    at /home/i.gouss/.npm/blacksmith/1.1.3/package/lib/blacksmith/common.js:69:11
    at Object.oncomplete (fs.js:107:15)

li656-170% node -v
v0.10.20

li656-170% cat /etc/debian_version
7.2

**Comment by tomtempest** [comment]
It worked for me this way:

git clone https://github.com/flatiron/blacksmith.git
cd blacksmith
npm install
cd test/fixtures/blog
../../../bin/blacksmith .
../../../node_modules/http-server/bin/http-server -e html

npm test fails.

The docs are very limited.
